[project]
name = "wildchat-classification-visualization"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets",
    "pyarrow",
    "streamlit",
    "orjson",
    "orjson",
    "watchdog"
]
